AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  EnvironmentName:
    Description: Name of environment
    Type: String

  NetworkEnvironmentName:
    Description: Name of network stack that created in challenge2
    Type: String

Resources:
  RoleForSSMAccess:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'

  ServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref RoleForSSMAccess

  WebAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to instance
      VpcId:
        Fn::ImportValue:
          !Sub ${NetworkEnvironmentName}-VPCID
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref ServerInstanceProfile
      KeyName: VocareumKey2
      ImageId: ami-0800fc0fa715fdcfe
      InstanceType: t3.small
      SecurityGroupIds: 
        - !Ref WebAccessSecurityGroup
      SubnetId: 
        Fn::ImportValue:
          !Sub ${NetworkEnvironmentName}-PrivSubnet
